// <auto-generated />
using System;
using LogiticaOC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogiticaOC.Infrastructure.Migrations
{
    [DbContext(typeof(OcLogisticaDbContext))]
    [Migration("20260623185017_SeedEstados")]
    partial class SeedEstados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogiticaOC.Domain.Entities.Entidad", b =>
                {
                    b.Property<int>("EntidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntidadId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EntidadId");

                    b.HasIndex("RazonSocial");

                    b.ToTable("Entidades", (string)null);
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.EstadoOC", b =>
                {
                    b.Property<int>("EstadoOcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoOcId"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstadoOcId");

                    b.ToTable("EstadosOC", (string)null);

                    b.HasData(
                        new
                        {
                            EstadoOcId = 1,
                            ColorHex = "#4f8ef7",
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            EstadoOcId = 2,
                            ColorHex = "#6f42c1",
                            Nombre = "Listo para Despacho"
                        },
                        new
                        {
                            EstadoOcId = 3,
                            ColorHex = "#f59e0b",
                            Nombre = "Entrega Parcial"
                        },
                        new
                        {
                            EstadoOcId = 4,
                            ColorHex = "#22c55e",
                            Nombre = "Cerrada"
                        },
                        new
                        {
                            EstadoOcId = 5,
                            ColorHex = "#6c757d",
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.EstadoProducto", b =>
                {
                    b.Property<int>("EstadoProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoProductoId"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstadoProductoId");

                    b.ToTable("EstadosProducto", (string)null);

                    b.HasData(
                        new
                        {
                            EstadoProductoId = 1,
                            ColorHex = "#28a745",
                            Nombre = "En Proceso"
                        },
                        new
                        {
                            EstadoProductoId = 2,
                            ColorHex = "#fd7e14",
                            Nombre = "Urgente Compras"
                        },
                        new
                        {
                            EstadoProductoId = 3,
                            ColorHex = "#0dcaf0",
                            Nombre = "Importación"
                        },
                        new
                        {
                            EstadoProductoId = 4,
                            ColorHex = "#ffc107",
                            Nombre = "Entrega Parcial"
                        },
                        new
                        {
                            EstadoProductoId = 5,
                            ColorHex = "#6c757d",
                            Nombre = "Cerrada"
                        },
                        new
                        {
                            EstadoProductoId = 6,
                            ColorHex = "#343a40",
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.Guia", b =>
                {
                    b.Property<int>("GuiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuiaId"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("FechaGuia")
                        .HasColumnType("date");

                    b.Property<string>("NumeroGuia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OcId")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("GuiaId");

                    b.HasIndex("OcId");

                    b.ToTable("Guias", (string)null);
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.HistorialOC", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"));

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OcId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsableAnterior")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponsableNuevo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HistorialId");

                    b.HasIndex("OcId");

                    b.ToTable("HistorialOC", (string)null);
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.OrdenCompra", b =>
                {
                    b.Property<int>("OcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OcId"));

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOcId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaDespacho")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaLlegadaCorreo")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("FechaSolicitada")
                        .HasColumnType("date");

                    b.Property<string>("LugarEntrega")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Movilidad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroOC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PDFAdjunto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PDFNombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDiasEstablecidos")
                        .HasColumnType("int");

                    b.HasKey("OcId");

                    b.HasIndex("EntidadId");

                    b.HasIndex("EstadoOcId");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("NumeroOC")
                        .IsUnique();

                    b.HasIndex("ResponsableId");

                    b.ToTable("OrdenCompra", (string)null);
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.OrdenCompraDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoProducto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EstadoProductoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoEntregaParcial")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OcId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("EstadoProductoId");

                    b.HasIndex("OcId");

                    b.ToTable("OrdenCompraDetalle", (string)null);
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.Responsable", b =>
                {
                    b.Property<int>("ResponsableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponsableId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ResponsableId");

                    b.ToTable("Responsables", (string)null);
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.Guia", b =>
                {
                    b.HasOne("LogiticaOC.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Guias")
                        .HasForeignKey("OcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.HistorialOC", b =>
                {
                    b.HasOne("LogiticaOC.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Historial")
                        .HasForeignKey("OcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.OrdenCompra", b =>
                {
                    b.HasOne("LogiticaOC.Domain.Entities.Entidad", "Entidad")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiticaOC.Domain.Entities.EstadoOC", "EstadoOC")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("EstadoOcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiticaOC.Domain.Entities.Responsable", "Responsable")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Entidad");

                    b.Navigation("EstadoOC");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.OrdenCompraDetalle", b =>
                {
                    b.HasOne("LogiticaOC.Domain.Entities.EstadoProducto", "EstadoProducto")
                        .WithMany("Detalles")
                        .HasForeignKey("EstadoProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiticaOC.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoProducto");

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.Entidad", b =>
                {
                    b.Navigation("OrdenesCompra");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.EstadoOC", b =>
                {
                    b.Navigation("OrdenesCompra");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.EstadoProducto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Guias");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("LogiticaOC.Domain.Entities.Responsable", b =>
                {
                    b.Navigation("OrdenesCompra");
                });
#pragma warning restore 612, 618
        }
    }
}
